apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: container1
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: container2
    image: redis:latest
    ports:
    - containerPort: 6379
  restartPolicy: Always